/home/kyudan/anaconda3/envs/py3.12/lib/python3.12/site-packages/datasets/load.py:1461: FutureWarning: The repository for librispeech_asr contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/librispeech_asr
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
Downloading builder script: 100%|██████████| 11.4k/11.4k [00:00<00:00, 10.6MB/s]
Downloading readme: 100%|██████████| 10.2k/10.2k [00:00<00:00, 14.3MB/s]
Downloading data: 100%|██████████| 338M/338M [00:45<00:00, 7.45MB/s]   
Downloading data: 100%|██████████| 314M/314M [00:43<00:00, 7.28MB/s]   
Downloading data: 100%|██████████| 347M/347M [00:31<00:00, 10.9MB/s]   
Downloading data: 100%|██████████| 329M/329M [00:34<00:00, 9.65MB/s]   
Downloading data: 100%|██████████| 6.39G/6.39G [10:49<00:00, 9.84MB/s]   
Downloading data:   2%|▏         | 385M/23.0G [00:38<38:14, 9.88MB/s]     
